### ISSUE TITLE
How can i get the quantity of single product

### ISSUE THREAD

**Issue by hassannissar** [syscover/shoppingcart#2]
**We can : Get the number of items in the cart, total items**
by  using method mention below.
 CartProvider::instance()->getQuantity()

But i want to find the quantity of of single product ?

![single_items_quantity_get](https://cloud.githubusercontent.com/assets/20722255/17244963/225a13ea-5539-11e6-8258-68700ec93581.png)

**Comment by carlospalacin** [comment]
Hi hassannissar!
You can use getQuantity() method from item object:

`
foreach(CartProvider::instance()->getCartItems() as $item)
{
  $item->getQuantity();
}
`
Regards!

**Comment by hassannissar** [comment]
Hi  i am using this package in my project,on local environment its working
good. But on live domain i am facing this type of error.
Class 'Syscover\ShoppingCart\ShoppingCartServiceProvider' not found
