### ISSUE TITLE
Class not found on live environment.But on local environment working good

### ISSUE THREAD

**Issue by hassannissar** [syscover/shoppingcart#3]
I am using this package with laravel 5.2 project. on local every thing working good but on live, I have found error
Class 'Syscover\ShoppingCart\ShoppingCartServiceProvider' not found

Issue resolved by using
php artisan vendor:publish
composer update

**Comment by hassannissar** [comment]
Issue resolved by using 
php artisan vendor:publish
composer update

**Comment by carlospalacin** [comment]
thanks for yours comments!
