### ISSUE TITLE
Get unit price without tax

### ISSUE THREAD

**Issue by gdhnz** [syscover/shoppingcart#7]
Is there an easy way to get a cart item's price excluding tax?

My items are added to the cart with tax but I'd like to build an invoice with prices excluding tax.

The only way I've found so far is to do something like `$item->subtotal / $item->quantity` and then round to 2 decimal places.

**Comment by carlospalacin** [comment]
Hi! 
yo can use

```
$item->getPrice()
```
If you have 
```
TAX_PRODUCT_DISPLAY_PRICES=1 //Excluding tax
```
environment variable, the price will be without tax.

**Comment by gdhnz** [comment]
I want to be able to display prices including tax to end users when adding/removing items to the cart but display prices excluding taxes when it comes to the invoices.

**Comment by gdhnz** [comment]
If I use `config(['shoppingCart.taxProductDisplayPrices' => 1]);` before initiating the cart to use for the invoice, then `$item->getPrice()` returns the price excluding tax.
